### PR TITLE
Delete a single essential file

### LINKED ISSUE #9: Make the experience last longer
Only delete one random file to make the 'experience' last longer:D
More fun and teasing than completely wiping everything...

### PR DESCRIPTION
**Pull request by cheriimoya**
closes #9

### CODE REVIEW

**Comment by amyipdev** [comment]
Perhaps this could be done in a fork?

**Comment by cheriimoya** [comment]
Do you mean a fork project or a fork process? @amyipdev

**Comment by amyipdev** [comment]
@cheriimoya A fork project.

**Comment by busybox11** [comment]
Yeah, this doesn't really belong here considering the very true nature of the project. It is named "Suicide Linux", not "Selfharm Linux".

**Review by SupaGamer2017 — APPROVED** [review]
Looks like this could be a cool idea. I'm looking forward to seeing a `selfharm-linux` fork in the future.

**Comment by RGBCube** [comment]
> Looks like this could be a cool idea. I'm looking forward to seeing a `selfharm-linux` fork in the future.

it is done https://github.com/RGBCube/selfharm-linux

**Pull request closed without merging**
